import type { SunsetLocationCandidate } from "./types";

export const goldenCheckCandidates: SunsetLocationCandidate[] = [
  {
    id: "vancouver-sunset-beach",
    name: "Sunset Beach",
    region: "vancouver-bc",
    kind: "beach",
    latitude: 49.2785,
    longitude: -123.1367,
    sources: ["osm-overpass", "google-places", "web-validation"],
    scenicTags: ["beach", "waterfront", "park"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "City of Vancouver: Sunset Beach",
        url: "https://vancouver.ca/parks-recreation-culture/sunset-beach.aspx",
        source: "web-validation",
        strength: "strong",
        confirms: ["beach", "waterfront", "public access", "dusk imagery"],
      },
    ],
  },
  {
    id: "vancouver-queen-elizabeth-park",
    name: "Queen Elizabeth Park",
    region: "vancouver-bc",
    kind: "elevated-park",
    latitude: 49.2417,
    longitude: -123.1127,
    sources: ["osm-overpass", "google-places", "web-validation"],
    scenicTags: ["park", "viewpoint", "tourism=viewpoint"],
    directionHint: "PANORAMA",
    hasWaterView: false,
    hasElevation: true,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "City of Vancouver: Queen Elizabeth Park",
        url: "https://vancouver.ca/parks-recreation-culture/queen-elizabeth-park.aspx",
        source: "web-validation",
        strength: "strong",
        confirms: ["highest point", "spectacular views", "photo backdrop"],
      },
    ],
  },
  {
    id: "vancouver-lighthouse-park",
    name: "Lighthouse Park",
    region: "vancouver-bc",
    kind: "lighthouse",
    latitude: 49.3307,
    longitude: -123.2649,
    sources: ["osm-overpass", "google-places", "open-photo", "web-validation"],
    scenicTags: ["park", "lighthouse", "tourism=viewpoint", "waterfront"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: true,
    publicAccess: true,
    photoReferenceCount: 3,
    references: [
      {
        title: "District of West Vancouver: Lighthouse Park",
        url: "https://westvancouver.ca/parks-recreation/parks-trails/lighthouse-park",
        source: "web-validation",
        strength: "strong",
        confirms: ["lighthouse viewpoint", "photographed landmark", "public park"],
      },
    ],
  },
  {
    id: "vancouver-english-bay-beach",
    name: "English Bay Beach",
    region: "vancouver-bc",
    kind: "beach",
    latitude: 49.286,
    longitude: -123.1425,
    sources: ["osm-overpass", "google-places", "web-validation"],
    scenicTags: ["beach", "waterfront", "park"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "English Bay, Vancouver",
        url: "https://en.wikipedia.org/wiki/English_Bay,_Vancouver",
        source: "web-validation",
        strength: "medium",
        confirms: ["sunset-watching beach", "public waterfront"],
      },
    ],
  },
  {
    id: "surrey-blackie-spit-park",
    name: "Blackie Spit Park",
    region: "surrey-bc",
    kind: "waterfront",
    latitude: 49.0572,
    longitude: -122.8829,
    sources: ["osm-overpass", "google-places", "open-photo", "web-validation"],
    scenicTags: ["park", "waterfront", "nature", "beach"],
    directionHint: "NW-W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "City of Surrey: Blackie Spit Park",
        url: "https://www.surrey.ca/parks-recreation/parks/blackie-spit-park",
        source: "web-validation",
        strength: "strong",
        confirms: ["stunning beach", "amazing views", "Mud Bay"],
      },
    ],
  },
  {
    id: "surrey-crescent-beach",
    name: "Crescent Beach",
    region: "surrey-bc",
    kind: "beach",
    latitude: 49.0523,
    longitude: -122.8836,
    sources: ["osm-overpass", "google-places", "open-photo", "web-validation"],
    scenicTags: ["beach", "waterfront", "neighbourhood"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "Crescent Beach, Surrey",
        url: "https://en.wikipedia.org/wiki/Crescent_Beach,_Surrey",
        source: "web-validation",
        strength: "medium",
        confirms: ["beachside community", "waterfront", "local landmarks"],
      },
    ],
  },
  {
    id: "surrey-mud-bay-park",
    name: "Mud Bay Park",
    region: "surrey-bc",
    kind: "waterfront",
    latitude: 49.0962,
    longitude: -122.8619,
    sources: ["osm-overpass", "web-validation"],
    scenicTags: ["park", "waterfront", "dyke", "bay"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 1,
    references: [
      {
        title: "City of Surrey: Mud Bay Park",
        url: "https://www.surrey.ca/parks-recreation/parks/mud-bay-park",
        source: "web-validation",
        strength: "medium",
        confirms: ["park", "bay", "public access", "waterfront"],
      },
    ],
  },
  {
    id: "surrey-brownsville-bar-park",
    name: "Brownsville Bar Park",
    region: "surrey-bc",
    kind: "waterfront",
    latitude: 49.2056,
    longitude: -122.8876,
    sources: ["osm-overpass", "web-validation"],
    scenicTags: ["park", "waterfront", "river"],
    directionHint: "NW-W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 1,
    references: [
      {
        title: "City of Surrey: Brownsville Bar Park",
        url: "https://www.surrey.ca/parks-recreation/parks/brownsville-bar-park",
        source: "web-validation",
        strength: "medium",
        confirms: ["park", "Fraser River", "public access", "waterfront"],
      },
    ],
  },
  {
    id: "surrey-serpentine-fen",
    name: "Serpentine Fen",
    region: "surrey-bc",
    kind: "trail",
    latitude: 49.0717,
    longitude: -122.7994,
    sources: ["osm-overpass", "web-validation"],
    scenicTags: ["trail", "wetland", "dyke", "nature"],
    directionHint: "PANORAMA",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 0,
    references: [
      {
        title: "Serpentine Wildlife Management Area",
        url: "https://en.wikipedia.org/wiki/Serpentine_Wildlife_Management_Area",
        source: "web-validation",
        strength: "weak",
        confirms: ["wetland", "public nature area", "open horizon"],
      },
    ],
  },
  {
    id: "coquitlam-rocky-point-park",
    name: "Rocky Point Park",
    region: "coquitlam-bc",
    kind: "waterfront",
    latitude: 49.2803,
    longitude: -122.8499,
    sources: ["osm-overpass", "open-photo", "web-validation"],
    scenicTags: ["park", "waterfront", "pier", "inlet"],
    directionHint: "W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "Rocky Point Park",
        url: "https://en.wikipedia.org/wiki/Rocky_Point_Park",
        source: "web-validation",
        strength: "medium",
        confirms: ["Burrard Inlet", "park", "pier", "public access"],
      },
    ],
  },
  {
    id: "coquitlam-old-orchard-park",
    name: "Old Orchard Park",
    region: "coquitlam-bc",
    kind: "waterfront",
    latitude: 49.2876,
    longitude: -122.8586,
    sources: ["osm-overpass", "web-validation"],
    scenicTags: ["park", "waterfront", "beach", "inlet"],
    directionHint: "S-W",
    hasWaterView: true,
    hasElevation: false,
    publicAccess: true,
    photoReferenceCount: 1,
    references: [
      {
        title: "Port Moody: Old Orchard Park",
        url: "https://www.portmoody.ca/en/recreation-parks-and-environment/old-orchard-park.aspx",
        source: "web-validation",
        strength: "medium",
        confirms: ["sandy beach", "park", "public access", "inlet"],
      },
    ],
  },
  {
    id: "coquitlam-belcarra-regional-park",
    name: "Belcarra Regional Park",
    region: "coquitlam-bc",
    kind: "waterfront",
    latitude: 49.316,
    longitude: -122.927,
    sources: ["osm-overpass", "open-photo", "web-validation"],
    scenicTags: ["regional park", "waterfront", "forest", "inlet"],
    directionHint: "PANORAMA",
    hasWaterView: true,
    hasElevation: true,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "Belcarra Regional Park",
        url: "https://en.wikipedia.org/wiki/T%C9%99mt%C9%99m%C3%ADx%CA%B7t%C9%99n/Belcarra_Regional_Park",
        source: "web-validation",
        strength: "medium",
        confirms: ["regional park", "ocean waterfront", "public access"],
      },
    ],
  },
  {
    id: "coquitlam-burnaby-mountain",
    name: "Burnaby Mountain",
    region: "coquitlam-bc",
    kind: "elevated-park",
    latitude: 49.2799,
    longitude: -122.9186,
    sources: ["osm-overpass", "open-photo", "web-validation"],
    scenicTags: ["park", "viewpoint", "mountain", "tourism=viewpoint"],
    directionHint: "PANORAMA",
    hasWaterView: true,
    hasElevation: true,
    publicAccess: true,
    photoReferenceCount: 2,
    references: [
      {
        title: "Burnaby Mountain",
        url: "https://en.wikipedia.org/wiki/Burnaby_Mountain",
        source: "web-validation",
        strength: "medium",
        confirms: ["mountain", "park", "viewpoint", "public access"],
      },
    ],
  },
];
